# PostgreSQL. Versions 9.1 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  username: rubyuser
  password: 1234
  host: localhost
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Rsas_development
  username: rubyuser
  password: 1234
  host: localhost
  encoding: utf8
  
  
test:
  <<: *default
  database: Rsas_test
  username: rubyuser
  password: 1234
  host: localhost
  encoding: utf8

production:
  <<: *default
  database: Rsas_production
  username: rubyuser
  password: 1234
  host: localhost
  encoding: utf8